

```{r}

setwd("~/Desktop/volcano-plot")
library(scales); library(dplyr); library(tidyr); library(tibble); library(stringr); library(ggplot2); library(cowplot); library(ggpubr)
select <- dplyr::select; rename <- dplyr::rename; mutate <- dplyr::mutate; 
summarize <- dplyr::summarize; arrange <- dplyr::arrange; slice <- dplyr::slice; filter <- dplyr::filter; recode<-dplyr::recode
style <- plotly::style
```


Make test dataset
```{r}
# https://github.com/SafetyGraphics/volcano-plot/issues/7
ae_vars = c("USUBJID", "AESEQ", "AESTDT", "AESTDY", "AEENDT", "AEENDY", "AETERM", "AEDECOD", "AEBODSYS", "AESER", "AEONGO", "AESEV", "AEREL", "AEOUT", "STUDYFL", "TRTEMFL")
dm_vars = c("SITE", "SITEID", "AGE", "SEX", "RACE", "ARM", "ARMCD", "SBJTSTAT", "RFSTDTC", "RFENDTC", "RFENDY", "SAFFL")
all_vars = c(ae_vars,dm_vars)

# https://github.com/phuse-org/phuse-scripts/tree/master/data/sdtm/TDF_SDTM_v1.0
library(haven)
library(readr)
adae <- haven::read_xpt("https://github.com/phuse-org/phuse-scripts/raw/master/data/adam/cdisc/adae.xpt") %>% select(USUBJID, TRTEMFL, SAFFL)
adsl <- haven::read_xpt("https://github.com/phuse-org/phuse-scripts/raw/master/data/adam/cdisc/adsl.xpt")
ae = read_xpt("data/ae.xpt") %>% select(-STUDYID, -DOMAIN )
dm = read_xpt("data/dm.xpt")%>% select(-STUDYID, -DOMAIN )
ds = read_xpt("data/ds.xpt")%>% select(-STUDYID, -DOMAIN ) %>% filter(EPOCH=="TREATMENT" & DSCAT=="DISPOSITION EVENT") %>% select(USUBJID,DSDECOD)

test_data = ae %>% 
    inner_join(dm,by="USUBJID") %>% 
    inner_join(adae, by="USUBJID") %>%
    left_join(ds, by="USUBJID") %>% 
    rename(AESTDT = AESTDTC, AEENDT = AEENDTC) %>%
    mutate(AEONGO = ifelse(AEENDT=="","Y","N"),
           STUDYFL = TRTEMFL, 
           SITE = SITEID,
           RFENDTC = as.Date(RFENDTC),
           AEENDT = as.Date(ifelse(AEENDT=="",NA,AEENDT)),
           RFENDY = as.Date(RFENDTC) - AEENDT,
           RFENDY = ifelse(AEENDT<RFENDTC, RFENDY+1, RFENDY),
           SBJTSTAT = case_when(DSDECOD=="COMPLETED"~"TREATMENT COMPLETED",
                                !is.na(DSDECOD) & DSDECOD!="COMPLETED"~"DISCONTINUED",
                                TRUE~"ONGOING"),
           AEREL = recode(AEREL,"PROBABLE"="Y","REMOTE"="Y","POSSIBLE"="Y","NONE"="N"),
           AEREL = ifelse(AEREL=="",NA,AEREL))

match_vars = all_vars[which(all_vars %in% colnames(test_data))]
match_vars
no_vars = all_vars[which(!all_vars %in% colnames(test_data))]
no_vars

test_data2 = test_data %>% select(match_vars)
write_csv(test_data2, path="data/test_data.csv")


```

